//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrpMon.CAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CripMonEntities : DbContext
    {
        public CripMonEntities()
            : base("name=CripMonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PA_Actualiza_Estado(string pUsuario, string pID_Transaccion_Monedero)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pID_Transaccion_MonederoParameter = pID_Transaccion_Monedero != null ?
                new ObjectParameter("pID_Transaccion_Monedero", pID_Transaccion_Monedero) :
                new ObjectParameter("pID_Transaccion_Monedero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualiza_Estado", pUsuarioParameter, pID_Transaccion_MonederoParameter);
        }
    
        public virtual int PA_Actualiza_Password(string pUsuario, string pClave, string pClaveNueva)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pClaveNuevaParameter = pClaveNueva != null ?
                new ObjectParameter("pClaveNueva", pClaveNueva) :
                new ObjectParameter("pClaveNueva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualiza_Password", pUsuarioParameter, pClaveParameter, pClaveNuevaParameter);
        }
    
        public virtual int PA_Actualiza_Usuario(string pUsuario, string pClave, string nombres, string apellidos, string correo_Electronico, string cartera_Criptomoneda)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var cartera_CriptomonedaParameter = cartera_Criptomoneda != null ?
                new ObjectParameter("Cartera_Criptomoneda", cartera_Criptomoneda) :
                new ObjectParameter("Cartera_Criptomoneda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Actualiza_Usuario", pUsuarioParameter, pClaveParameter, nombresParameter, apellidosParameter, correo_ElectronicoParameter, cartera_CriptomonedaParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Empresa_Result> PA_bsc_Empresa(Nullable<int> pEmpresa)
        {
            var pEmpresaParameter = pEmpresa.HasValue ?
                new ObjectParameter("pEmpresa", pEmpresa) :
                new ObjectParameter("pEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Empresa_Result>("PA_bsc_Empresa", pEmpresaParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Idioma_Result> PA_bsc_Idioma(Nullable<byte> idioma)
        {
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("Idioma", idioma) :
                new ObjectParameter("Idioma", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Idioma_Result>("PA_bsc_Idioma", idiomaParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Mensaje_Result> PA_bsc_Mensaje(Nullable<byte> pEstado, Nullable<byte> pUsuario)
        {
            var pEstadoParameter = pEstado.HasValue ?
                new ObjectParameter("pEstado", pEstado) :
                new ObjectParameter("pEstado", typeof(byte));
    
            var pUsuarioParameter = pUsuario.HasValue ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Mensaje_Result>("PA_bsc_Mensaje", pEstadoParameter, pUsuarioParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Menu_Result> PA_bsc_Menu(Nullable<byte> idioma)
        {
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("Idioma", idioma) :
                new ObjectParameter("Idioma", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Menu_Result>("PA_bsc_Menu", idiomaParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Notificaciones_Result> PA_bsc_Notificaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Notificaciones_Result>("PA_bsc_Notificaciones");
        }
    
        public virtual ObjectResult<PA_bsc_Porcentajes_Result> PA_bsc_Porcentajes(string pUsuario, Nullable<byte> pIdioma)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pIdiomaParameter = pIdioma.HasValue ?
                new ObjectParameter("pIdioma", pIdioma) :
                new ObjectParameter("pIdioma", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Porcentajes_Result>("PA_bsc_Porcentajes", pUsuarioParameter, pIdiomaParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Producto_Result> PA_bsc_Producto(Nullable<byte> idioma)
        {
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("Idioma", idioma) :
                new ObjectParameter("Idioma", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Producto_Result>("PA_bsc_Producto", idiomaParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Transaccion_1_Usuario_Result> PA_bsc_Transaccion_1_Usuario(string pUsuario)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Transaccion_1_Usuario_Result>("PA_bsc_Transaccion_1_Usuario", pUsuarioParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Transacciones_Result> PA_bsc_Transacciones(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Transacciones_Result>("PA_bsc_Transacciones", usuarioParameter);
        }
    
        public virtual ObjectResult<PA_bsc_Vista_Result> PA_bsc_Vista(string pVista, Nullable<byte> pIdioma)
        {
            var pVistaParameter = pVista != null ?
                new ObjectParameter("pVista", pVista) :
                new ObjectParameter("pVista", typeof(string));
    
            var pIdiomaParameter = pIdioma.HasValue ?
                new ObjectParameter("pIdioma", pIdioma) :
                new ObjectParameter("pIdioma", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_bsc_Vista_Result>("PA_bsc_Vista", pVistaParameter, pIdiomaParameter);
        }
    
        public virtual ObjectResult<PA_Gancias_Usuario_Result> PA_Gancias_Usuario(string pUsuario)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Gancias_Usuario_Result>("PA_Gancias_Usuario", pUsuarioParameter);
        }
    
        public virtual int PA_Ins_Usuario_Arbol(string pUsuario)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Ins_Usuario_Arbol", pUsuarioParameter);
        }
    
        public virtual int PA_MensajeLeido(Nullable<long> pMensaje)
        {
            var pMensajeParameter = pMensaje.HasValue ?
                new ObjectParameter("pMensaje", pMensaje) :
                new ObjectParameter("pMensaje", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MensajeLeido", pMensajeParameter);
        }
    
        public virtual ObjectResult<PA_PaqueteActual_Result> PA_PaqueteActual(string pUsuario, Nullable<byte> idioma)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("Idioma", idioma) :
                new ObjectParameter("Idioma", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_PaqueteActual_Result>("PA_PaqueteActual", pUsuarioParameter, idiomaParameter);
        }
    
        public virtual ObjectResult<PA_Transaccion_Result> PA_Transaccion(string pTransaccion_Monedero, Nullable<int> pMonedero, byte[] pObservacion_1, string pUsuario, string pjsonResult, Nullable<int> pProducto, string pAmount, Nullable<int> pTimeOut, string pStatus_Url, string pQrcode_Url, string pAddress)
        {
            var pTransaccion_MonederoParameter = pTransaccion_Monedero != null ?
                new ObjectParameter("pTransaccion_Monedero", pTransaccion_Monedero) :
                new ObjectParameter("pTransaccion_Monedero", typeof(string));
    
            var pMonederoParameter = pMonedero.HasValue ?
                new ObjectParameter("pMonedero", pMonedero) :
                new ObjectParameter("pMonedero", typeof(int));
    
            var pObservacion_1Parameter = pObservacion_1 != null ?
                new ObjectParameter("pObservacion_1", pObservacion_1) :
                new ObjectParameter("pObservacion_1", typeof(byte[]));
    
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pjsonResultParameter = pjsonResult != null ?
                new ObjectParameter("pjsonResult", pjsonResult) :
                new ObjectParameter("pjsonResult", typeof(string));
    
            var pProductoParameter = pProducto.HasValue ?
                new ObjectParameter("pProducto", pProducto) :
                new ObjectParameter("pProducto", typeof(int));
    
            var pAmountParameter = pAmount != null ?
                new ObjectParameter("pAmount", pAmount) :
                new ObjectParameter("pAmount", typeof(string));
    
            var pTimeOutParameter = pTimeOut.HasValue ?
                new ObjectParameter("pTimeOut", pTimeOut) :
                new ObjectParameter("pTimeOut", typeof(int));
    
            var pStatus_UrlParameter = pStatus_Url != null ?
                new ObjectParameter("pStatus_Url", pStatus_Url) :
                new ObjectParameter("pStatus_Url", typeof(string));
    
            var pQrcode_UrlParameter = pQrcode_Url != null ?
                new ObjectParameter("pQrcode_Url", pQrcode_Url) :
                new ObjectParameter("pQrcode_Url", typeof(string));
    
            var pAddressParameter = pAddress != null ?
                new ObjectParameter("pAddress", pAddress) :
                new ObjectParameter("pAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Transaccion_Result>("PA_Transaccion", pTransaccion_MonederoParameter, pMonederoParameter, pObservacion_1Parameter, pUsuarioParameter, pjsonResultParameter, pProductoParameter, pAmountParameter, pTimeOutParameter, pStatus_UrlParameter, pQrcode_UrlParameter, pAddressParameter);
        }
    
        public virtual int PA_Usuario(string pUsuario, string pNombres, string pApellidos, string pCorreo_Electronico, string pClave, string pUsuario_Padre, string pCartera_Criptomoneda)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pNombresParameter = pNombres != null ?
                new ObjectParameter("pNombres", pNombres) :
                new ObjectParameter("pNombres", typeof(string));
    
            var pApellidosParameter = pApellidos != null ?
                new ObjectParameter("pApellidos", pApellidos) :
                new ObjectParameter("pApellidos", typeof(string));
    
            var pCorreo_ElectronicoParameter = pCorreo_Electronico != null ?
                new ObjectParameter("pCorreo_Electronico", pCorreo_Electronico) :
                new ObjectParameter("pCorreo_Electronico", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            var pUsuario_PadreParameter = pUsuario_Padre != null ?
                new ObjectParameter("pUsuario_Padre", pUsuario_Padre) :
                new ObjectParameter("pUsuario_Padre", typeof(string));
    
            var pCartera_CriptomonedaParameter = pCartera_Criptomoneda != null ?
                new ObjectParameter("pCartera_Criptomoneda", pCartera_Criptomoneda) :
                new ObjectParameter("pCartera_Criptomoneda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Usuario", pUsuarioParameter, pNombresParameter, pApellidosParameter, pCorreo_ElectronicoParameter, pClaveParameter, pUsuario_PadreParameter, pCartera_CriptomonedaParameter);
        }
    
        public virtual ObjectResult<string> PA_Usuario_Arbol(string pUsuario)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_Usuario_Arbol", pUsuarioParameter);
        }
    
        public virtual ObjectResult<PA_Usuario_Auth_Result> PA_Usuario_Auth(string pUsuario, string pClave)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pClaveParameter = pClave != null ?
                new ObjectParameter("pClave", pClave) :
                new ObjectParameter("pClave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Usuario_Auth_Result>("PA_Usuario_Auth", pUsuarioParameter, pClaveParameter);
        }
    
        public virtual int PA_Usuario_Bit_Default(string pUsuario, Nullable<bool> pBit_Default)
        {
            var pUsuarioParameter = pUsuario != null ?
                new ObjectParameter("pUsuario", pUsuario) :
                new ObjectParameter("pUsuario", typeof(string));
    
            var pBit_DefaultParameter = pBit_Default.HasValue ?
                new ObjectParameter("pBit_Default", pBit_Default) :
                new ObjectParameter("pBit_Default", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_Usuario_Bit_Default", pUsuarioParameter, pBit_DefaultParameter);
        }
    }
}
